export const listConstants = {
    GET_STORE_BRANCHES_REQUEST: 'GET_STORE_BRANCHES_REQUEST',
    GET_STORE_BRANCHES_SUCCESS: 'GET_STORE_BRANCHES_SUCCESS',
    GET_STORE_BRANCHES_FAILURE: 'GET_STORE_BRANCHES_FAILURE',

    SET_SEARCH: 'SET_SEARCH',
    CLEAR_SEARCH: 'CLEAR_SEARCH',
    SET_STORE_AREA: 'SET_STORE_AREA',
    SET_STORE_CITY: 'SET_STORE_CITY',
};
